# Import all tool modules to trigger registration
from tools import (
    delivery,
    lotto,
    fine_dust,
    han_river,
    kbo,
    kleague,
    spell_check,
    law_search,
    sillok,
    blue_ribbon,
    cheap_gas,
    real_estate,
    zipcode,
    weather_info,
    daiso,
    coupang,
    kakao_bar,
    olive_young,
    subway,
    used_car,
    lck,
    hwp,
)
